
package se.recan.app.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarServiceInterface", targetNamespace = "http://ws.app.recan.se/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CarServiceInterface {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.app.recan.se/CarServiceInterface/setSpeedRequest", output = "http://ws.app.recan.se/CarServiceInterface/setSpeedResponse")
    public void setSpeed(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0);

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.app.recan.se/CarServiceInterface/getSpeedRequest", output = "http://ws.app.recan.se/CarServiceInterface/getSpeedResponse")
    public double getSpeed();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.app.recan.se/CarServiceInterface/setDistanceRequest", output = "http://ws.app.recan.se/CarServiceInterface/setDistanceResponse")
    public void setDistance(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0);

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.app.recan.se/CarServiceInterface/getDistanceRequest", output = "http://ws.app.recan.se/CarServiceInterface/getDistanceResponse")
    public double getDistance();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.app.recan.se/CarServiceInterface/toStringRequest", output = "http://ws.app.recan.se/CarServiceInterface/toStringResponse")
    public String toString();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.app.recan.se/CarServiceInterface/getTimeRequest", output = "http://ws.app.recan.se/CarServiceInterface/getTimeResponse")
    public double getTime();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.app.recan.se/CarServiceInterface/setTimeRequest", output = "http://ws.app.recan.se/CarServiceInterface/setTimeResponse")
    public void setTime(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0);

}
