package se.recan.app.mbt.login;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "Login.graphml")
public interface Login {

    @Vertex()
    void s_Login() throws Exception ;

    @Edge()
    void a_Login();

    @Edge()
    void a_Stop();

    @Edge()
    void a_Start();

    @Vertex()
    void s_Verify() throws Exception ;

    @Edge()
    void a_Verify();

    @Vertex()
    void s_Exit();

    @Vertex()
    void s_Stop();

    @Edge()
    void a_Exit();

    @Vertex()
    void s_Start();
}
